'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ExcelRecoveryAddin.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; onLoad=&quot;Ribbon_OnLoad&quot;&gt;
        '''	&lt;ribbon&gt;
        '''		&lt;tabs&gt;
        '''			&lt;tab id=&quot;ExcelRecoveryAddinTab&quot; label=&quot;Excel Recovery Add-in&quot;&gt;
        '''
        '''				&lt;group id=&quot;ExcelRecoveryAddinGroup1&quot; label=&quot;General&quot;&gt;
        '''					&lt;button id=&quot;Ribbon_Button_SelectFile&quot; size=&quot;large&quot; label=&quot;Select File&quot; onAction=&quot;On_Ribbon_Button_SelectFile_Clicked&quot; getImage=&quot;On_Ribbon_Button_SelectFile_GetImage&quot; /&gt;
        '''					&lt;button id=&quot;Ribbon_Button_PreviousVersion&quot; size=&quot;large&quot; label=&quot;Find Previous Versions&quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Excel_Main() As String
            Get
                Return ResourceManager.GetString("Excel_Main", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ExcelFix() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExcelFix", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExternalReferences() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExternalReferences", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FindVersions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindVersions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Folder_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ManualCalculations() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ManualCalculations", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MSOpenAndExtract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MSOpenAndExtract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MSOpenAndRepair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MSOpenAndRepair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NonMSDataExtract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NonMSDataExtract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NonMSDataExtract2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NonMSDataExtract2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OpenInExcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenInExcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OpenInSafeMode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenInSafeMode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OpenInWordPad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenInWordPad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAsHTML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAsHTML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAsSYLK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAsSYLK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SelectFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZipRepairTry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZipRepairTry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
